module.exports = {
  forgetPasswordController: require("./forgetpassword"),
  loginController: require("./login.controller"),
  signupController: require("./signup.controller"),
  addNighboursQuestionAnswerController: require("./addNeighboursQuestionAnswers.controller"),
  getNearByProjectOfflineController: require("./getProjectDetail.controller"),
  updatePushTokenController: require("./updatePushToken.controller"),
  dashBoardController: require("./dashboard.controller"),
  adminController: require("./admin.controller"),
  commonController: require("./common.controller"),
  businessController: require("./business.controller"),
  userController: require("./user.controller"),
  projectController: require("./project.controller"),
  docuSignController: require("./docuSign.controller"),
  getProjectDetailController: require("./getProjectDetail.controller"),
  addCommentOnProjectController: require("./addCommentOnProjects.controller"),
  addLikesOnProjectController: require("./addLikesOnProject.controller"),
  getCommentController: require("./getComment.controller"),
  volunteerAndRefer: require("./volunteerAndRefer.controller"),
  pushNotificationController: require("./pushNotification.controller"),
  cardsController: require("./card.controller"),
  reportController: require("./report.Controller"),
  stateController: require("./state.Controller"),
  notificationController: require("./notification.controller"),
  emailController: require("./email.controller"),
  reportListController: require("./reportList.controller"),
  okToContactController: require("./okToContact.controller")
};
